### ISSUE TITLE
The concept of an interval might currently be a bit unclear to users

### ISSUE THREAD

**Issue by sandve** [bionumpy/bionumpy#12]
The file intervals.py has several functions that operate on "intvervals", but since these are functions (with untyped parameters) it is not from the function interfaces obvious what they assume about what an interval is and how a user is assumed to work with intervals. The only class is "RawInterval", which has only start and end. The function sort_intervals also uses only these two attributes. However, the function pileup assumes another attribute chromosome. Functions like sort_intervals are decorated by ChromosomeMap, which explains this difference, but the user would need some guidance as to how one is supposed to work with this - how to get chromosome-grouped data, what functionality is available to what etc. And if the user forgets to group data by chromosome, will then a function like sort_intervals silently sort data irrespective of chromosome? (i.e. should these functions assert that data either do not have a chromosome attribute or that all values for this attribute are equal?!). Finally, is there a particular reason why pileup is not ChromosomeMap-ed?

**Comment by knutdrand** [comment]
Yes, maybe it's more clear if these functions take starts and ends in as parameters? It will now silently sort intervals from different chromosomes if that's provided. Only way to prevent this, is to assume that they intervals should not have different chromosomes. But this would fail if it's used on i.e gene data where the "contig"-identifier is different

**Comment by sandve** [comment]
You mean if contigs are provided as "chromosomes"? But isn't this the same with contigs also - aren't start and end-coordinates typically relative to their contigs, so that they should not be sorted across contigs? Agree that providing separate start and end could be an option. Or alternatively that it would assert that chromosome is either not present or that it contains always the same value (if contig should behave like I assumed above..)
