### ISSUE TITLE
Define an explicit strategy for how to help users discover central functions for bionumpy objects they are working with 

### ISSUE THREAD

**Issue by sandve** [bionumpy/bionumpy#15]
As an example, let's say a user reads in a bed file as follows: 
bnp.open("myfile.bed").read()

The user can now see that this gives an object of class "Interval".
By following the code, the users will find that this is of class "bnpdataclass".

However, from there on, it is not so obvious to navigate further according to needs.

For instance, let's say a user realise that these intervals should be grouped by chromosome. Indeed, the codebase contains a function for this, in the form of the function groupby from the module "bionumpy.groupby". However, it is currently not so clear what path the user is meant to take from the Interval/bnpdataclass object that he/she has, so as to finally arrive at the groupby. Seeing which central functaionality would have been easier if they had been available as a method groupby of an interval object (class), so one here need a good alternative strategy to guide the user in the right direction. Perhaps the users should learn to follow the class to a documentation entry for that class (Interval) that would mention the central functionality available?! Or is it possible to point the user in the right direction more directly in the code?

**Comment by knutdrand** [comment]
Yes, I see two solutions. Either groupby, as well as other central functionality needs to lie at the toplevel of the module, and be well documented and pointed to by different tutorials etc. Or we add groupby, sortby etc to bnpdataclass.
