### ISSUE TITLE
Add possibility to work with a concept aka GlobalGenomeOffset?

### ISSUE THREAD

**Issue by sandve** [bionumpy/bionumpy#18]
Given length and ordering of a set of chromosomes, any genome coordinate can be easily converted to an integer (global offset) by adding a global chromosome start position to the relative chromosome position for a coordinate. It would seem possible to implement conversion to such global offsets based on a chr vector and a start vector in an efficient manner!?
DNA sequence of the genome could correspondingly be considered as a single long sequence vector (concatenated by chromosome order).

If so, this could have certain advantages/uses:
- It would allow to index across the genome in a single operation (retrieve DNA sequence for genomic intervals across the full genome in one operation). This would be particularly useful (effective) for genomes containing a large number of chrs (assembly with many contigs, or something like relative positions within transcripts for RNA analysis or such..). 
- When chunking is needed, it would allow to relate only to a single splitting of the genome (a split into chunks - without any splitting into chromsomes)
- It would allow to sort whole genome data in a simple way (plain sorting of the global offset)

What would be needed is perhaps just a genome map (class that represents a list of chromosomes with defined size), a function that converts intervals from chr coordinates to global offsets based on the genome map, and a function that concatenates sequences per chr based on the genome map. This would allow to convert sequence and intervals to a global vector and indexes of such a vector, respectively.  It could possibly also be based on some concept of implicit encoding.

**Comment by knutdrand** [comment]
I think something like this will be useful, especially for settings with many contigs, where it will have performance benefits. 
 I think maybe RaggedArray  can be used to make it user friendly, and avid the user having to deal with the concept of linearized coordinates. For the seqeunces it would be an EncodedRaggedArray of sequences, which under the hood is just concatenated sequences with linearized coordinates. We would only need a mapping chromosome_name  -> row_number. Then we can also use lexsort to easily sort data across contigs. One way to implement this is with a ChromosomeNameEncoding, where encode is from chromosome_name->number, and decode is number->chromosome_name. Bam uses this anyway, so it's at least partly implemented already.  When it comes to chunking, one benefit of working with chromosome-grouped data is to make sure that data from different streams are synched, this would not happen with buffer-size chunked data from different streams.
