### ISSUE TITLE
Printing a streamable changes its state

### ISSUE THREAD

**Issue by sandve** [bionumpy/bionumpy#19]
Is this desired behavior? The for-loop below will only get out one chunk, since the "print(streamable)" eats the second chunk.. If the print(streamable) is removed, it instead gets two chunks in the loop..

streamable = bnp.open("example_data/gc_test_multichr.fa").read_chunks(50)
for i,chunk in enumerate(streamable):
    print(f"Seq {i}: {chunk.sequence[0]}")
    print(streamable)

Based on file:
>chr1
ACGGCAACACATTTTTACATTTTAT
>chr2
GTTAACCACACTTTGAGAAA

**Comment by knutdrand** [comment]
Very undesired behaviour. Fixing it in a refactor now

**Comment by knutdrand** [comment]
Should be fixed now
