### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by jsgounot** [bionumpy/bionumpy#39]
Hi,

I would like to know if you would consider packaging your library to bioconda or not. Thanks for the great work.

Regards,
JS

**Comment by knutdrand** [comment]
Hi! 
Yes, we hope to get it up on Conda quite soon.

Thanks for the nice feedback!

**Comment by telatin** [comment]
Hi, I added the recipes:
https://github.com/bioconda/bioconda-recipes/pull/38644 (npstructures, done)
https://github.com/bioconda/bioconda-recipes/pull/38630 (bionumpy, ongoing)

Hope this helps, if there are changes needed, I'm happy to assist.

**Comment by jsgounot** [comment]
Great, thanks!

**Comment by knutdrand** [comment]
That's super, thank you @telatin !
