### ISSUE TITLE
DOC: supported file format duplication

### ISSUE THREAD

**Issue by tylerjereddy** [bionumpy/bionumpy#67]
Looks like `fasta / fa` is listed twice at: https://github.com/bionumpy/bionumpy/blob/ddc91b17b2960fc0c7fc1c21447bd509e02fd576/docs_source/source/supported_file_formats.rst?plain=1#L12

I suspect one of them needs to be changed to fastq perhaps?

**Comment by knutdrand** [comment]
Thanks for the catch :)
