### ISSUE TITLE
MAINT: warning on import

### ISSUE THREAD

**Issue by tylerjereddy** [bionumpy/bionumpy#68]
* bionumpy version: v1.0.4 (from PyPI)
* Python version: `3.12.0`
* Operating System: Ubuntu x86_64 Linux

A `pip` install of bionumpy in a fresh Python `3.12.0` venv results in a warning on a plain import:

```
>>> import bionumpy
/home/treddy/py_312_bionumpy_review/lib/python3.12/site-packages/bionumpy/encodings/vcf_encoding.py:98: RuntimeWarning: invalid value encountered in cast
  _lookup[[ord(c) for c in ('0', '1', '.')]] = np.array([0, 1, np.nan])
>>> 
```

**Comment by knutdrand** [comment]
Thanks, fixed
