### ISSUE TITLE
Behavior of merge_intervals

### ISSUE THREAD

**Issue by sandve** [bionumpy/bionumpy#9]
* bionumpy version: latest

Based on a gene file from here: 
https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/

Why is the following code:
print(merge_intervals(bnp.open("hg38.ensGene.gtf").read_chunk()))

Showing mutliple interals ending at the same coordinate 14409 after merge_intervals?:
              chromosome                   source             feature_type                    start                      end                    score                   strand                    phase                atributes
                     chr1                  ensGene               transcript                    11869                    14409                        .                        +                      254  gene_id "ENSG0000022...
                     chr1                  ensGene                     exon                    12613                    14409                        .                        +                      254  gene_id "ENSG0000022...

**Comment by knutdrand** [comment]
Intervals needs to be sorted  for merge_intervals. Added assert and documentation
